name: Test and Deploy

on:
  push:
    branches: [ "main" ]


jobs:
  
  deploy-app:
 
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Deploy Application to Code Engine
        uses: ./.github/actions/ce-action
        with:
          api-key: ${{ secrets.IBM_IAM_API_KEY }}
          region: 'ca-tor'
          project: 'LR-PR-CA-TOR'
          component: 'app'
          name: 'hello'
          build-source: './app'



