name: Test and Deploy

on:
  push:
    branches: [ "main" ]


jobs:
  
  deploy-app:
 
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Deploy Application to Code Engine
        uses: skywalkeretw/ibm-code-engine-github-action@v1
        with:
          api-key: ${{ secrets.IBM_IAM_API_KEY }}
          resource-group: 'Default'
          region: 'eu-de'
          project: 'LR-DEMO'
          entity: 'app'
          name: 'go-app'
          build-source: './app'

  test-deploy-function:

    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    
    - name: Run test
      uses: skywalkeretw/ibm-code-engine-function-test-github-action@v1
      with:
        runtime: nodejs-18
        source-dir: func-nodejs

    - name: Deploy JavaScript Function to Code Engine
      uses: skywalkeretw/ibm-code-engine-github-action@v1
      with:
        api-key: ${{ secrets.IBM_IAM_API_KEY }}
        resource-group: 'Default'
        region: 'eu-de'
        project: 'LR-DEMO'
        entity: 'fn'
        runtime: nodejs-18 
        name: 'my-js-fn'
        build-source: './func-nodejs'


