name: Deploy to code Engine

on:
  push:
    branches: [ "main" ]


jobs:
  
  deploy:
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Application to Code Engine
        uses: ./.github/actions/ce-action
        with:



